name: tarjimakitoblar
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.5
  url_launcher:
  flutter_slidable: ^0.5.5
  card_swiper: ^2.0.4
  card_loading: ^0.1.5
  scaled_list: ^2.0.0
  clippy_flutter: ^1.1.1
  fluttertoast: 7.1.1
  image_picker: ^0.8.4+10
  provider: ^6.0.3
  shared_preferences: ^2.0.13
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  firebase_storage: ^10.3.0
  cloud_firestore: ^3.1.5
  firebase_messaging: ^11.4.2
  slimy_card: ^1.0.4
  flutter_pdfview: ^1.0.4
  #path
  file_picker: ^5.0.0
  path: ^1.8.1
  path_provider: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/books/
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

    - family: Nottingsam_Demo
      fonts:
        - asset: assets/fonts/Nottingsam_Demo.ttf

    - family: BebasNeue-Regular
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf